version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: virko
    ports:
      - "3306:3306"
    volumes:
      - virko_db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  onlyoffice:
    image: onlyoffice/documentserver
    ports:
      - "8081:80"
    environment:
      - JWT_ENABLED=false
      - ALLOW_PRIVATE_LOCAL_IPS_IN_REQUESTS=true

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
    depends_on:
      - db
    entrypoint: >
      /bin/sh -c "npm install --prefix /data node-red-node-mysql node-red-dashboard && npm start --cache /data/.npm -- --userDir /data"

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  virko_db:
